language: python
services:
  - mysql
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
# command to run tests
script:
  - pytest
  - coverage run -m pytest

after_success:
  - coveralls
